spring:
  application:
    name: jobhunter

  datasource:
    url: jdbc:mysql://localhost:3306/jobhunter
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo bảng nếu chưa có
    show-sql: true # Hiển thị câu lệnh SQL trên terminal

  data:
    web:
      pageable:
        one-indexed-parameters: true # Start page = 1, not 0

  servlet:
    multipart:
      max-file-size: 50MB # Giới hạn file upload 50MB
      max-request-size: 50MB # Giới hạn request form data 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: minhducdtr70@gmail.com
    password: tmwajnnjtkovbcfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

hoidanit:
  jwt:
    base64-secret: 3j1Q8gWEoZXQV3TBds6CWdALIx2+TsEMsC+G8lYtQTU086bwXzI8JqQV+T1lEoDbZVY48QQUFPqgcTtjMXpPKw==
    access-token-validity-in-seconds: 8640000 # 100 ngày cho access token
    refresh-token-validity-in-seconds: 8640000 # 100 ngày cho refresh token

  upload-file:
    base-uri: file:///D:/upload/ # Đường dẫn upload file từ máy tính

